// Code generated by go-enum, DO NOT EDIT.
package singlefile

import (
	"github.com/globalsign/mgo/bson"

	mongo "go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/bsontype"
)

func (cookie_enum Cookie) GetBSON() (interface{}, error) {
	err := cookie_enum.Validate() 
	if err != nil {
		return nil, err
	}

	return cookie_enum.String(), nil
}

func (cookie_enum *Cookie) SetBSON(raw bson.Raw) error {
	var str string

	if len(raw.Data) == 0 {
		return bson.ErrSetZero
	}
	
	err := raw.Unmarshal(&str)
	if err != nil {
		return err
	}

	enum, err := CookieFromString(str)
	if err != nil {
		return err
	}

	*cookie_enum = *enum
	return nil
}

func (cookie_enum *Cookie) UnmarshalBSON(data []byte) error {
	return cookie_enum.SetBSON(bson.Raw{
		Kind: bson.ElementString,
		Data: data,
	})
}

func (cookie_enum Cookie) MarshalBSONValue() (bsontype.Type, []byte, error) {
	err := cookie_enum.Validate()
	if err != nil {
		return bsontype.Undefined,nil, err
	}

	return mongo.MarshalValue(cookie_enum.String())
}
