// Code generated by go-enum, DO NOT EDIT.
package singlefile

import (
	"database/sql/driver"
	"fmt"
)

func (cookie_enum Cookie) Value() (driver.Value, error) {
	return cookie_enum.String(), cookie_enum.Validate()
}

func (cookie_enum *Cookie) Scan(val any) error {
	var str string

	switch v := val.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("unsupported type %T", v)
	}

	enum, err := CookieFromString(str)
	if err != nil {
		return err
	}

	*cookie_enum = *enum
	return nil
}
