// Code generated by go-enum, DO NOT EDIT.
package singlefile

import (
	"encoding/xml"
)

func (cookie_enum Cookie) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	err := cookie_enum.Validate() 
	if err != nil {
		return err
	}

	return e.EncodeElement(cookie_enum.String(), start)
}

func (cookie_enum *Cookie) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var str string
	if err := d.DecodeElement(&str, &start); err != nil {
		return err
	}

	enum, err := CookieFromString(str)
	if err != nil {
		return err
	}

	*cookie_enum = *enum
	return nil
}
