// Code generated by go-enum, DO NOT EDIT.
package singlefile


func (cookie_enum Cookie) MarshalText() ([]byte, error) {
	return []byte(cookie_enum.String()), nil
}

func (cookie_enum *Cookie) UnmarshalText(text []byte) (error) {
	enum, err := CookieFromString(string(text))
	if err != nil {
		return err
	}

	*cookie_enum = *enum

	return nil
}
