// Code generated by go-enum, DO NOT EDIT.
package singlefile

import (
	"fmt"
)

func AllBiscuits() []Biscuit {
	return []Biscuit{
		BiscuitDigestive,
		BiscuitHobnob,
		BiscuitNice,
		BiscuitJammieDodger,
		BiscuitShortbread,
		BiscuitGingerNut,
	}
}

func validBiscuits() []Biscuit {
	return []Biscuit{
		BiscuitDigestive,
		BiscuitHobnob,
		BiscuitNice,
		BiscuitJammieDodger,
		BiscuitShortbread,
		BiscuitGingerNut,
	}
}

func ToBiscuit(value int) Biscuit {
	biscuit_enum := Biscuit(value)
	switch biscuit_enum {
	case BiscuitDigestive, BiscuitHobnob, BiscuitNice, BiscuitJammieDodger, BiscuitShortbread, BiscuitGingerNut:
		return biscuit_enum
	default:
		return BiscuitDigestive
	}
}

func (biscuit_enum Biscuit) String() string {
	switch biscuit_enum {
	case BiscuitDigestive:
		return "biscuit_digestive"
	case BiscuitHobnob:
		return "biscuit_hobnob"
	case BiscuitNice:
		return "biscuit_nice"
	case BiscuitJammieDodger:
		return "biscuit_jammie_dodger"
	case BiscuitShortbread:
		return "biscuit_shortbread"
	case BiscuitGingerNut:
		return "biscuit_ginger_nut"
	default:
		return BiscuitDigestive.String()
	}
}

func BiscuitFromString(val string) (*Biscuit, error) {
	valid := validBiscuits()	
	for i := range valid {
		if valid[i].String() == val {
			return &valid[i], nil
		}
	}	

	return nil, fmt.Errorf("%s is not a valid Biscuit", val)
}

func (biscuit_enum Biscuit) Validate() error {
	_, err := BiscuitFromString(biscuit_enum.String())
	return err
}
