// Code generated by go-enum, DO NOT EDIT.
package singlefile

import (
	"fmt"
	"io"
	"strconv"
)

func (cookie_enum Cookie) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(cookie_enum.String()))
}

func (cookie_enum *Cookie) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum value %T must be a string", val)
	}

	enum, err := CookieFromString(str)
	if err != nil {
		return err
	}
	 
	*cookie_enum = *enum
	return nil
}
