// Code generated by go-enum, DO NOT EDIT.
package singlefile


func (biscuit_enum Biscuit) MarshalText() ([]byte, error) {
	return []byte(biscuit_enum.String()), nil
}

func (biscuit_enum *Biscuit) UnmarshalText(text []byte) (error) {
	enum, err := BiscuitFromString(string(text))
	if err != nil {
		return err
	}

	*biscuit_enum = *enum

	return nil
}
