// Code generated by go-enum, DO NOT EDIT.
package day

import (
	"database/sql/driver"
	"fmt"
)

func (day_enum Day) Value() (driver.Value, error) {
	return day_enum.String(), day_enum.Validate()
}

func (day_enum *Day) Scan(val any) error {
	var str string

	switch v := val.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("unsupported type %T", v)
	}

	enum, err := DayFromString(str)
	if err != nil {
		return err
	}

	*day_enum = *enum
	return nil
}
