// Code generated by go-enum, DO NOT EDIT.
package day

import (
	"encoding/xml"
)

func (day_enum Day) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	err := day_enum.Validate() 
	if err != nil {
		return err
	}

	return e.EncodeElement(day_enum.String(), start)
}

func (day_enum *Day) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var str string
	if err := d.DecodeElement(&str, &start); err != nil {
		return err
	}

	enum, err := DayFromString(str)
	if err != nil {
		return err
	}

	*day_enum = *enum
	return nil
}
