// Code generated by go-enum, DO NOT EDIT.
package day


func (day_enum Day) MarshalText() ([]byte, error) {
	return []byte(day_enum.String()), nil
}

func (day_enum *Day) UnmarshalText(text []byte) (error) {
	enum, err := DayFromString(string(text))
	if err != nil {
		return err
	}

	*day_enum = *enum

	return nil
}
