// Code generated by go-enum, DO NOT EDIT.
package directions

import (
	"strconv"
	"strings"
)

func (cardinal_enum Cardinal) MarshalJSON() ([]byte, error) {
	err := cardinal_enum.Validate() 
	if err != nil {
		return nil, err
	}

	return []byte(strconv.Quote(cardinal_enum.String())), nil
}

func (cardinal_enum *Cardinal) UnmarshalJSON(val []byte) error {
	str := string(val)
	str = strings.Trim(str, "\"")

	enum, err := CardinalFromString(str)
	if err != nil {
		return err
	}

	*cardinal_enum = *enum
	return nil
}
