// Code generated by go-enum, DO NOT EDIT.
package directions

import (
	"strconv"
	"strings"
)

func (direction_enum Direction) MarshalJSON() ([]byte, error) {
	err := direction_enum.Validate() 
	if err != nil {
		return nil, err
	}

	return []byte(strconv.Quote(direction_enum.String())), nil
}

func (direction_enum *Direction) UnmarshalJSON(val []byte) error {
	str := string(val)
	str = strings.Trim(str, "\"")

	enum, err := DirectionFromString(str)
	if err != nil {
		return err
	}

	*direction_enum = *enum
	return nil
}
