// Code generated by go-enum, DO NOT EDIT.
package day

import (
	"github.com/globalsign/mgo/bson"
)

func (day_enum Day) GetBSON() (interface{}, error) {
	err := day_enum.Validate() 
	if err != nil {
		return nil, err
	}

	return day_enum.String(), nil
}

func (day_enum *Day) SetBSON(raw bson.Raw) error {
	var str string
	
	err := raw.Unmarshal(&str)
	if err != nil {
		return err
	}

	enum, err := DayFromString(str)
	if err != nil {
		return err
	}

	*day_enum = *enum
	return nil
}
