// Code generated by go-enum, DO NOT EDIT.
package multiple

import (
	"encoding/xml"
)

func (biscuit_enum Biscuit) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	err := biscuit_enum.Validate() 
	if err != nil {
		return err
	}

	return e.EncodeElement(biscuit_enum.String(), start)
}

func (biscuit_enum *Biscuit) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var str string
	if err := d.DecodeElement(&str, &start); err != nil {
		return err
	}

	enum, err := BiscuitFromString(str)
	if err != nil {
		return err
	}

	*biscuit_enum = *enum
	return nil
}
