// Code generated by go-enum, DO NOT EDIT.
package multiple

import (
	"github.com/globalsign/mgo/bson"
)

func (biscuit_enum Biscuit) GetBSON() (interface{}, error) {
	err := biscuit_enum.Validate() 
	if err != nil {
		return nil, err
	}

	return biscuit_enum.String(), nil
}

func (biscuit_enum *Biscuit) SetBSON(raw bson.Raw) error {
	var str string
	
	err := raw.Unmarshal(&str)
	if err != nil {
		return err
	}

	enum, err := BiscuitFromString(str)
	if err != nil {
		return err
	}

	*biscuit_enum = *enum
	return nil
}
