// Code generated by go-enum, DO NOT EDIT.
package multiple

import (
	"fmt"
	"io"
	"strconv"
)

func (biscuit_enum Biscuit) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(biscuit_enum.String()))
}

func (biscuit_enum *Biscuit) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum value %T must be a string", val)
	}

	enum, err := BiscuitFromString(str)
	if err != nil {
		return err
	}
	 
	*biscuit_enum = *enum
	return nil
}
