// Code generated by go-enum, DO NOT EDIT.
package multiple

import (
	"strconv"
	"strings"
)

func (cookie_enum Cookie) MarshalJSON() ([]byte, error) {
	err := cookie_enum.Validate() 
	if err != nil {
		return nil, err
	}

	return []byte(strconv.Quote(cookie_enum.String())), nil
}

func (cookie_enum *Cookie) UnmarshalJSON(val []byte) error {
	str := string(val)
	str = strings.Trim(str, "\"")

	enum, err := CookieFromString(str)
	if err != nil {
		return err
	}

	*cookie_enum = *enum
	return nil
}
