// Code generated by go-enum, DO NOT EDIT.
package day

import (
	"strconv"
	"strings"
)

func (day_enum Day) MarshalJSON() ([]byte, error) {
	err := day_enum.Validate() 
	if err != nil {
		return nil, err
	}

	return []byte(strconv.Quote(day_enum.String())), nil
}

func (day_enum *Day) UnmarshalJSON(val []byte) error {
	str := string(val)
	str = strings.Trim(str, "\"")

	enum, err := DayFromString(str)
	if err != nil {
		return err
	}

	*day_enum = *enum
	return nil
}
